apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-frontend
  labels:
    app: chat-app
    tier: frontend
  namespace: chat-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-app
      tier: frontend
  template:
    metadata:
      labels:
        app: chat-app
        tier: frontend
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: frontend
          # chat-app/app/frontend の Dockerfile からビルドしたイメージ
          # Updated: 2025-10-04 - Added Socket.IO proxy support
          image: ghcr.io/rockyx2000/chat-frontend:sha-b4b3d6c
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-backend
  labels:
    app: chat-app
    tier: backend
  namespace: chat-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-app
      tier: backend
  template:
    metadata:
      labels:
        app: chat-app
        tier: backend
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      initContainers:
        - name: migrate
          image: ghcr.io/rockyx2000/chat-backend:sha-b4b3d6c
          command: ["sh", "-c", "npx prisma migrate deploy"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DATABASE_URL
      containers:
        - name: backend
          # chat-app/app/backend の Dockerfile からビルドしたイメージ
          image: ghcr.io/rockyx2000/chat-backend:sha-b4b3d6c
          ports:
            - containerPort: 8080
          env:
            - name: BACKEND_PORT
              value: "8080"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DATABASE_URL
          resources:
            requests:
              cpu: 50m
              memory: 256
            limits:
              cpu: 300m
              memory: 512Mi


