apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull-secret
  namespace: chat-app
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: cm9ja3l4MjAwMDpnaXRodWJfcGF0XzExQVJIRURXUTB3NTZ6a3RoTTlqU1NfS0VrazhuS1ZZQnloSHM3MHZ4Q1hsRzhLNXFTeXlHR0VOaUxtZ1o2ZmlHT0tBRVdHS0hPbUMxUFRDSEo=