apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat-app
  annotations:
    kubernetes.io/ingress.class: nginx
  namespace: chat-app
spec:
  selector:
    name: nginx-ingress-microk8s
  type: LoadBalancer
  rules:
    - host: chatapp.rkapp.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chat-frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: chat-backend
                port:
                  number: 80
          - path: /socket.io
            pathType: Prefix
            backend:
              service:
                name: chat-backend
                port:
                  number: 80
