apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat-app
  annotations:
    kubernetes.io/ingress.class: nginx
  namespace: chat-app
spec:
  rules:
    # - host: REPLACE_WITH_DOMAIN
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chat-frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: chat-backend
                port:
                  number: 80
          - path: /socket.io
            pathType: Prefix
            backend:
              service:
                name: chat-backend
                port:
                  number: 80
